In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')

In [3]:
movies_ratings = pd.merge(left=ratings,right=movies,on='movieId')

In [4]:
movies_ratings = movies_ratings[['userId', 'movieId', 'title', 'genres', 'rating', 'timestamp']]

In [5]:
movies_ratings_pivot = pd.pivot_table(index='userId',columns='title',values='rating',data=movies_ratings)
movies_ratings_pivot

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.5,3.5,NaN,NaN,NaN
609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,4.0,3.5,3.0,NaN,NaN,2.0,1.5,NaN,NaN

In [6]:
booleanDf = movies_ratings_pivot.notna()
booleanDf

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
607,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
608,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
609,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
610,True,False,False,False,False,False,False,False,True,False,...,False,True,True,True,False,False,True,True,False,False

In [7]:
frequent_itemsets = apriori(booleanDf, min_support=0.11, use_colnames=True)
frequent_itemsets

        support                                           itemsets
0      0.178689                     (2001: A Space Odyssey (1968))
1      0.131148                                       (300 (2007))
2      0.121311                   (40-Year-Old Virgin, The (2005))
3      0.263934                (Ace Ventura: Pet Detective (1994))
4      0.144262            (Ace Ventura: When Nature Calls (1995))
...         ...                                                ...
40271  0.111475  (Star Wars: Episode V - The Empire Strikes Bac...
40272  0.111475  (Star Wars: Episode V - The Empire Strikes Bac...
40273  0.113115  (Star Wars: Episode V - The Empire Strikes Bac...
40274  0.113115  (Star Wars: Episode V - The Empire Strikes Bac...
40275  0.111475  (Star Wars: Episode V - The Empire Strikes Bac...

[40276 rows x 2 columns]

In [8]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(2001: A Space Odyssey (1968)),(Blade Runner (1982)),0.178689,0.203279,0.127869,0.715596,3.520272,0.091545,2.801375
1,(2001: A Space Odyssey (1968)),(Forrest Gump (1994)),0.178689,0.539344,0.140984,0.788991,1.462871,0.044609,2.183108
2,(2001: A Space Odyssey (1968)),"(Matrix, The (1999))",0.178689,0.455738,0.134426,0.752294,1.650716,0.052991,2.197207
3,(2001: A Space Odyssey (1968)),(Pulp Fiction (1994)),0.178689,0.503279,0.131148,0.733945,1.458327,0.041217,1.866987
4,(2001: A Space Odyssey (1968)),"(Silence of the Lambs, The (1991))",0.178689,0.457377,0.132787,0.743119,1.624741,0.051059,2.112354
...,...,...,...,...,...,...,...,...,...
277818,(Lord of the Rings: The Fellowship of the Ring...,(Star Wars: Episode V - The Empire Strikes Bac...,0.152459,0.127869,0.111475,0.731183,5.718224,0.091981,3.244328
277819,(Lord of the Rings: The Fellowship of the Ring...,(Star Wars: Episode V - The Empire Strikes Bac...,0.150820,0.132787,0.111475,0.739130,5.566291,0.091449,3.324317
277820,"(Lord of the Rings: The Return of the King, Th...",(Star Wars: Episode V - The Empire Strikes Bac...,0.152459,0.132787,0.111475,0.731183,5.506438,0.091231,3.226033
277821,"(Lord of the Rings: The Return of the King, Th...",(Star Wars: Episode V - The Empire Strikes Bac...,0.154098,0.122951,0.111475,0.723404,5.883688,0.092529,3.170870
277822,"(Lord of the Rings: The Two Towers, The (2002)...",(Star Wars: Episode V - The Empire Strikes Bac...,0.155738,0.124590,0.111475,0.715789,5.745152,0.092072,3.080146

In [9]:
rules = rules.sort_values(by=['confidence','lift'], ascending=[False,False])
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
263491,(Star Wars: Episode V - The Empire Strikes Bac...,(Star Wars: Episode VI - Return of the Jedi (1...,0.111475,0.163934,0.111475,1.0,6.100000,0.093201,inf
270903,(Star Wars: Episode V - The Empire Strikes Bac...,(Star Wars: Episode VI - Return of the Jedi (1...,0.113115,0.163934,0.113115,1.0,6.100000,0.094571,inf
243741,(Pirates of the Caribbean: The Curse of the Bl...,(Star Wars: Episode V - The Empire Strikes Bac...,0.111475,0.190164,0.111475,1.0,5.258621,0.090277,inf
228165,"(Lord of the Rings: The Two Towers, The (2002)...",(Star Wars: Episode V - The Empire Strikes Bac...,0.111475,0.198361,0.111475,1.0,5.041322,0.089363,inf
114515,"(Fifth Element, The (1997), Terminator, The (1...",(Star Wars: Episode V - The Empire Strikes Bac...,0.113115,0.211475,0.113115,1.0,4.728682,0.089194,inf
...,...,...,...,...,...,...,...,...,...
29549,"(Jurassic Park (1993), Terminator 2: Judgment ...",(Apollo 13 (1995)),0.229508,0.329508,0.160656,0.7,2.124378,0.085031,2.234973
12083,"(Forrest Gump (1994), Sixth Sense, The (1999))",(Star Wars: Episode V - The Empire Strikes Bac...,0.229508,0.345902,0.160656,0.7,2.023697,0.081268,2.180328
37608,"(Braveheart (1995), Silence of the Lambs, The ...","(Shawshank Redemption, The (1994), Forrest Gum...",0.245902,0.378689,0.172131,0.7,1.848485,0.079011,2.071038
6569,"(Fugitive, The (1993), Silence of the Lambs, T...",(Braveheart (1995)),0.229508,0.388525,0.160656,0.7,1.801688,0.071486,2.038251
5404,"(Batman (1989), Jurassic Park (1993))","(Shawshank Redemption, The (1994))",0.229508,0.519672,0.160656,0.7,1.347003,0.041387,1.601093

In [10]:
def get_recommendations(movies_list,output_data):
    recommendations = []
    for index, row in rules.iterrows():
        ok = False
        for x in row['antecedents']:
            if x in movies_list:
                ok = True
                break

        if ok:
            for x in row['consequents']:
                recommendations.append(x)
    temp = recommendations
    recommendations = []
    for i in temp:
        if len(recommendations)==4:
            break
        if i not in recommendations:
            recommendations.append(i)
    output_data.append(recommendations)
    return output_data

In [30]:
input_data=pd.read_csv('sample_test.tsv', sep='\t')

In [31]:
input_movies = input_data['movies']
temp = input_movies
input_movies = []
for i in temp:
    i = i.split('\n')
    input_movies.append(i)

In [32]:
output_data = []
for i in input_movies:
    output_data = get_recommendations(i,output_data)
    while(len(output_data[-1])<4):
        for j in range(len(movies['title'])):
            if (movies['title'][j] not in output_data[-1] and movies['title'][j] not in i):
                output_data[-1].append(movies['title'][j])
                break;

In [33]:
import csv

header = ['movies', 'recommendations']
output_data_csv = []

for i in range(0,len(input_movies)):
    output_data_csv.append([input_movies[i],",".join(output_data[i])])

with open('output.csv', 'w', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    for i in output_data_csv:
        writer.writerow(i)

In [26]:
movies['title'][0]

'Toy Story (1995)'